pull_request_rules:
  - name: automatic merge on CI success and review - pr
    conditions:
      - status-success=Build mathlib (leanprover-community/lean:3.5.1)
      - "#changes-requested-reviews-by=0"
      - base=master
      - label=ready-to-merge
      - approved-reviews-by=@leanprover-community/mathlib-maintainers
    actions:
     delete_head_branch: {}
     merge:
        method: squash
        strict: smart
        strict_method: merge
 # second condition necessary, as mergify was failing if the travis "pr" build
 # finished before the travis "push" build due to branch protection setting requiring
 # the "push" build to complete before a merge
  - name: automatic merge on CI success and review - push
    conditions:
      - status-success=Build mathlib (leanprover-community/lean:3.5.1)
      - "#changes-requested-reviews-by=0"
      - base=master
      - label=ready-to-merge
      - approved-reviews-by=@leanprover-community/mathlib-maintainers
    actions:
     delete_head_branch: {}
     merge:
        method: squash
        strict: smart
        strict_method: merge
  # Allows PRs with [skip ci] and [ci skip] to be merged without waiting for Travis.
  - name: automatic merge on CI success and review - push
    conditions:
      - title~=\[skip ci\]|\[ci skip\]
      - "#changes-requested-reviews-by=0"
      - base=master
      - label=ready-to-merge
      - approved-reviews-by=@leanprover-community/mathlib-maintainers
    actions:
     delete_head_branch: {}
     merge:
        method: squash
        strict: smart
        strict_method: merge

 # In practice this turns out to be really annoying.
 # - name: remove outdated reviews
 #   conditions:
 #     - base=master
 #   actions:
 #     dismiss_reviews:
 #       approved: True
